// Profissões do C2X (prod_careli, tabela professions) — usadas no seletor de
// profissão do cadastro E no envio (users.profession_id). Gerado do banco.
import type { C2xOption } from "./c2x-fields";

export const C2X_PROFISSOES: C2xOption[] = [
  { id: 1, label: "ACABADOR(A) DE MÁRMORE" },
  { id: 2, label: "AÇOUGUEIRO(A)" },
  { id: 3, label: "ADMINISTRADOR(A)" },
  { id: 4, label: "ADVOGADO(A)" },
  { id: 5, label: "AGENTE DE AEROPORTO" },
  { id: 6, label: "AGENTE DE SAÚDE" },
  { id: 7, label: "AGENTE DE SERVIÇO ESCOLAR" },
  { id: 8, label: "AGENTE DE TURISMO" },
  { id: 9, label: "AGENTE PENITENCIÁRIO(A)" },
  { id: 10, label: "AGRICULTOR(A)" },
  { id: 11, label: "AJUDANTE" },
  { id: 12, label: "ALMOXARIFE" },
  { id: 13, label: "ANALISTA ADMINISTRATIVO(A)" },
  { id: 14, label: "ANALISTA CONTÁBIL" },
  { id: 15, label: "ANALISTA DE RECURSOS HUMANOS" },
  { id: 16, label: "ANALISTA DE SISTEMAS" },
  { id: 17, label: "ANALISTA DE SUPRIMENTOS" },
  { id: 18, label: "ANALISTA FINANCEIRO(A)" },
  { id: 19, label: "ANALISTA JURÍDICO(A)" },
  { id: 20, label: "ANALISTA LOGÍSTICO(A)" },
  { id: 21, label: "ANTROPÓLOGO(A)" },
  { id: 22, label: "APOSENTADO(A)" },
  { id: 23, label: "ARQUITETO(A)" },
  { id: 108, label: "ARQUITETO(A) DE CLOUD" },
  { id: 24, label: "ARTESÃO(A)" },
  { id: 26, label: "ARTISTA" },
  { id: 27, label: "ASSESSOR(A)" },
  { id: 28, label: "ASSISTENTE ADMINISTRATIVO(A)" },
  { id: 29, label: "ASSISTENTE CONTÁBIL" },
  { id: 30, label: "ASSISTENTE DE EDUCAÇÃO" },
  { id: 31, label: "ASSISTENTE SOCIAL" },
  { id: 32, label: "ATENDENTE" },
  { id: 33, label: "ATLETA" },
  { id: 34, label: "AUDITOR(A)" },
  { id: 35, label: "AUTÔNOMO(A)" },
  { id: 36, label: "AUXILIAR ADMINISTRATIVO(A)" },
  { id: 37, label: "AUXILIAR CONTÁBIL" },
  { id: 38, label: "AUXILIAR DE ENGENHARIA" },
  { id: 39, label: "AUXILIAR DE LIMPEZA" },
  { id: 40, label: "AUXILIAR DE SERVIÇOS MECÂNICOS" },
  { id: 41, label: "BABÁ" },
  { id: 42, label: "BALCONISTA" },
  { id: 43, label: "BANCÁRIO(A)" },
  { id: 44, label: "BARBEIRO(A)" },
  { id: 45, label: "BIÓLOGO(A)" },
  { id: 46, label: "BIOMÉDICO(A)" },
  { id: 47, label: "BOMBEIRO(A)" },
  { id: 48, label: "BORRACHEIRO(A)" },
  { id: 49, label: "CABELEIREIRO(A)" },
  { id: 50, label: "CALDEIREIRO(A)" },
  { id: 51, label: "CAMINHONEIRO(A)" },
  { id: 52, label: "CARPINTEIRO(A)" },
  { id: 53, label: "CHAVEIRO(A)" },
  { id: 54, label: "CHEFE DE COZINHA" },
  { id: 55, label: "CIENTISTA DE COMPUTAÇÃO" },
  { id: 56, label: "COLADOR(A) DE ARTEFATOS" },
  { id: 57, label: "COLETOR(A)" },
  { id: 58, label: "COMERCIANTE" },
  { id: 59, label: "COMISSÁRIO(A) DE BORDO" },
  { id: 60, label: "COMPRADOR(A)" },
  { id: 61, label: "COMUNICÓLOGO(A)" },
  { id: 62, label: "CONCHEIRO(A)" },
  { id: 63, label: "CONFEITEIRO(A)" },
  { id: 65, label: "CONSULTOR(A)" },
  { id: 66, label: "CONSULTOR(A) DE VENDAS" },
  { id: 67, label: "CONTADOR(A)" },
  { id: 68, label: "CONTROLADOR(A) DE PRODUÇÃO" },
  { id: 69, label: "COORDENADOR(A)" },
  { id: 70, label: "COORDENADOR(A) DE LOGÍSTICA" },
  { id: 71, label: "COORDENADOR(A) FINANCEIRO(A)" },
  { id: 72, label: "CORRETOR(A) DE IMÓVEIS" },
  { id: 73, label: "CORRETOR(A) DE SEGUROS" },
  { id: 74, label: "COSTUREIRO(A)" },
  { id: 75, label: "COZINHEIRO(A)" },
  { id: 76, label: "CUIDADOR(A) DE IDOSO" },
  { id: 77, label: "DELEGADO(A)" },
  { id: 78, label: "DENTISTA" },
  { id: 79, label: "DESENVOLVEDOR(A)" },
  { id: 80, label: "DESIGNER DE CÍLIOS" },
  { id: 81, label: "DESIGNER DE INTERIORES" },
  { id: 82, label: "DESIGNER DE PRODUTOS" },
  { id: 83, label: "DESIGNER GRÁFICO" },
  { id: 84, label: "DESPACHANTE" },
  { id: 86, label: "DIRETOR(A)" },
  { id: 87, label: "DO LAR" },
  { id: 88, label: "ECONOMISTA" },
  { id: 89, label: "EDUCADOR(A)" },
  { id: 90, label: "ELETRICISTA" },
  { id: 91, label: "EMPREENDEDOR(A)" },
  { id: 92, label: "EMPREITEIRO(A)" },
  { id: 93, label: "EMPRESÁRIO(A)" },
  { id: 94, label: "ENCANADOR(A)" },
  { id: 95, label: "ENCARREGADO(A) DE MANUTENÇÃO" },
  { id: 96, label: "ENCARREGADO(A) DE MONTAGEM" },
  { id: 97, label: "ENCARREGADO(A) DE OBRAS" },
  { id: 98, label: "ENFERMEIRO(A)" },
  { id: 99, label: "ENGENHEIRO(A)" },
  { id: 100, label: "ENGENHEIRO(A) AGRÔNOMO(A)" },
  { id: 101, label: "ENGENHEIRO(A) AMBIENTAL" },
  { id: 102, label: "ENGENHEIRO(A) CIVIL" },
  { id: 103, label: "ENGENHEIRO(A) DE PRODUÇÃO" },
  { id: 104, label: "ENGENHEIRO(A) DE SOFTWARE" },
  { id: 105, label: "ENGENHEIRO(A) ELETRICISTA" },
  { id: 106, label: "ENGENHEIRO(A) MECÂNICO(A)" },
  { id: 107, label: "ESCREVENTE" },
  { id: 143, label: "ESPECIALISTA EM MARKETING" },
  { id: 109, label: "ESTAGIÁRIO(A)" },
  { id: 110, label: "ESTETICISTA" },
  { id: 111, label: "ESTILISTA" },
  { id: 112, label: "ESTUDANTE" },
  { id: 113, label: "FABRICADOR(A) DE GRANITO" },
  { id: 114, label: "FARMACÊUTICO(A)" },
  { id: 115, label: "FERRAMENTEIRO(A)" },
  { id: 116, label: "FISIOTERAPEUTA" },
  { id: 117, label: "FOTÓGRAFO(A)" },
  { id: 118, label: "FRENTISTA" },
  { id: 119, label: "GARÇOM" },
  { id: 120, label: "GEÓLOGO(A)" },
  { id: 121, label: "GERENTE" },
  { id: 122, label: "GESSEIRO(A)" },
  { id: 123, label: "GESTOR(A) DE ESTOQUE" },
  { id: 85, label: "INFLUENCIADOR(A) DIGITAL" },
  { id: 124, label: "INSPETOR(A)" },
  { id: 125, label: "INSPETOR(A) DE MANUTENÇÃO" },
  { id: 126, label: "INSPETOR(A) DE SOLDA" },
  { id: 127, label: "INSTALADOR(A) DE DRYWALL" },
  { id: 128, label: "INSTRUTOR(A)" },
  { id: 129, label: "JARDINEIRO(A)" },
  { id: 130, label: "JORNALISTA" },
  { id: 131, label: "LANTERNEIRO(A)" },
  { id: 132, label: "LATICINISTA" },
  { id: 133, label: "LEITURISTA" },
  { id: 134, label: "LÍDER DE CALDERARIA" },
  { id: 135, label: "LÍDER DE MANUTENÇÃO INDUSTRIAL" },
  { id: 136, label: "LÍDER DE PRODUÇÃO" },
  { id: 137, label: "LOJISTA" },
  { id: 138, label: "LOMBADOR(A)" },
  { id: 139, label: "MANICURE" },
  { id: 141, label: "MAQUIADOR(A)" },
  { id: 142, label: "MARCENEIRO(A)" },
  { id: 144, label: "MARMORARISTA" },
  { id: 145, label: "MASSOTERAPEUTA" },
  { id: 146, label: "MECÂNICO(A)" },
  { id: 147, label: "MÉDICO(A)" },
  { id: 148, label: "MÉDICO(A) VETERINÁRIO(A)" },
  { id: 149, label: "MESTRE DE OBRAS" },
  { id: 150, label: "METALÚRGICO(A)" },
  { id: 151, label: "MINISTRO(A) DE CULTO RELIGIOSO" },
  { id: 152, label: "MONTADOR(A)" },
  { id: 153, label: "MONTADOR(A) DE EVENTOS" },
  { id: 154, label: "MONTADOR(A) DE MÓVEIS" },
  { id: 155, label: "MOTORISTA" },
  { id: 156, label: "MÚSICO(A)" },
  { id: 157, label: "NUTRICIONISTA" },
  { id: 158, label: "OFICIAL DE MANUTENÇÃO" },
  { id: 140, label: "OPERADOR(A) DE COQUERIA" },
  { id: 159, label: "OPERADOR(A) DE LOGÍSTICA" },
  { id: 160, label: "OPERADOR(A) DE MÁQUINAS" },
  { id: 177, label: "OPERADOR(A) DE PLATAFORMA" },
  { id: 161, label: "OPERADOR(A) DE POSTO" },
  { id: 162, label: "OPERADOR(A) DE PRODUÇÃO" },
  { id: 163, label: "OPERADOR(A) DE SOM" },
  { id: 164, label: "OPERÁRIO(A)" },
  { id: 165, label: "ORÇAMENTISTA" },
  { id: 166, label: "PADEIRO(A)" },
  { id: 167, label: "PEDREIRO(A)" },
  { id: 168, label: "PEDRISTA" },
  { id: 169, label: "PENSIONISTA" },
  { id: 170, label: "PERFUMISTA" },
  { id: 171, label: "PERSONAL TRAINER" },
  { id: 172, label: "PESCADOR(A)" },
  { id: 173, label: "PINTOR(A)" },
  { id: 174, label: "PIZZAIOLO(A)" },
  { id: 175, label: "PLANEJADOR(A) DE MANUTENÇÃO" },
  { id: 176, label: "PLANEJADOR(A) MECÂNICO(A)" },
  { id: 178, label: "POLICIAL" },
  { id: 179, label: "POLICIAL MILITAR" },
  { id: 180, label: "PORTEIRO(A)" },
  { id: 181, label: "PREPARADOR(A) DE FERRAMENTAS" },
  { id: 182, label: "PRODUTOR(A) DE EVENTOS" },
  { id: 25, label: "PROFISSÃO NÃO DECLARADA" },
  { id: 184, label: "PROGRAMADOR(A)" },
  { id: 185, label: "PROJETISTA" },
  { id: 186, label: "PROMOTOR(A) DE VENDAS" },
  { id: 187, label: "PSICANALISTA" },
  { id: 188, label: "PSICÓLOGO(A)" },
  { id: 189, label: "PUBLICITÁRIO(A)" },
  { id: 190, label: "RECEPCIONISTA" },
  { id: 191, label: "RECREADOR(A)" },
  { id: 192, label: "REPOSITOR(A)" },
  { id: 193, label: "REPRESENTANTE COMERCIAL" },
  { id: 194, label: "SECRETÁRIO(A)" },
  { id: 195, label: "SEGURANÇA" },
  { id: 196, label: "SERRALHEIRO(A)" },
  { id: 197, label: "SERVIDOR(A) PÚBLICO(A)" },
  { id: 198, label: "SILVICULTOR(A)" },
  { id: 199, label: "SOCIOEDUCADOR(A)" },
  { id: 200, label: "SOLDADOR(A)" },
  { id: 201, label: "SUPERVISOR(A)" },
  { id: 202, label: "TABELIÃO(A)" },
  { id: 203, label: "TÉCNICO(A)" },
  { id: 204, label: "TÉCNICO(A) AGRÍCOLA" },
  { id: 205, label: "TÉCNICO(A) AMBIENTAL" },
  { id: 206, label: "TÉCNICO(A) BANCÁRIO" },
  { id: 207, label: "TÉCNICO(A) DE ROBÓTICA" },
  { id: 208, label: "TÉCNICO(A) EM ANÁLISES CLÍNICAS" },
  { id: 209, label: "TÉCNICO(A) EM AUTOMAÇÃO" },
  { id: 210, label: "TÉCNICO(A) EM ELETROMECÂNICA" },
  { id: 211, label: "TÉCNICO(A) EM ELETRÔNICA" },
  { id: 213, label: "TÉCNICO(A) EM ELETROTÉCNICA" },
  { id: 214, label: "TÉCNICO(A) EM ENFERMAGEM" },
  { id: 215, label: "TÉCNICO(A) EM INFORMÁTICA" },
  { id: 216, label: "TÉCNICO(A) EM INSTRUMENTAÇÃO" },
  { id: 217, label: "TÉCNICO(A) EM LABORATÓRIO" },
  { id: 218, label: "TÉCNICO(A) EM MANUTENÇÃO" },
  { id: 219, label: "TÉCNICO(A) EM MANUTENÇÃO AERONÁUTICA" },
  { id: 220, label: "TÉCNICO(A) EM MANUTENÇÃO DE ELEVADORES" },
  { id: 221, label: "TÉCNICO(A) EM MANUTENÇÃO E PLANEJAMENTO" },
  { id: 222, label: "TÉCNICO(A) EM MECÂNICA" },
  { id: 223, label: "TÉCNICO(A) EM MECÂNICA HIDRÁULICA" },
  { id: 64, label: "TÉCNICO(A) EM OBRAS" },
  { id: 224, label: "TÉCNICO(A) EM PROCESSOS" },
  { id: 225, label: "TÉCNICO(A) EM REFRIGERAÇÃO E CLIMATIZAÇÃO" },
  { id: 226, label: "TÉCNICO(A) EM SEGURANÇA DO TRABALHO" },
  { id: 227, label: "TÉCNICO(A) EM TELECOMUNICAÇÕES" },
  { id: 228, label: "TÉCNICO(A) INDUSTRIAL" },
  { id: 229, label: "TÉCNICO(A) OPERADOR" },
  { id: 231, label: "TOPÓGRAFO(A)" },
  { id: 230, label: "TORNEIRO(A) MECÂNICO(A)" },
  { id: 232, label: "TRABALHADOR(A) RURAL" },
  { id: 233, label: "TROCADOR(A) DE MOLDE" },
  { id: 234, label: "VENDEDOR(A)" },
  { id: 235, label: "VIGILANTE" },
  { id: 236, label: "VISTORIADOR(A)" },
];
