import type { AttendancePriority } from "@/modules/attendance/types";

export type GuardianMockClient = {
  id: string;
  nome: string;
  cpf: string;
  telefone: string;
  idade: string;
  sexo: string;
  estadoCivil: string;
  profissao: string;
  renda: string;
  cidade: string;
  escolaridade: string;
  empreendimento: string;
  unidadeLote: string;
  quadra: string;
  lote: string;
  area: string;
  valorUnidade: number;
  parcelasTotal: number;
  parcelasLiquidadas: number;
  parcelasVencidas: number;
  parcelasAVencer: number;
  saldoAtraso: number;
  atrasoDias: number;
  scoreRisco: number;
  prioridade: AttendancePriority;
  responsavel: "Gustavo Freitas" | "Cinthia Cruz";
  status: "Em negociação" | "Contato programado" | "Escalado" | "Aguardando retorno" | "Proposta enviada" | "Regularizado" | "A vencer";
  perfilParcela: "Ato" | "Sinal" | "Parcela";
  vencimento: string;
  recuperado: number;
  segundaUnidade?: {
    empreendimento: string;
    unidadeLote: string;
    quadra: string;
    lote: string;
    area: string;
    valorUnidade: number;
  };
};

export const guardianMockClients: GuardianMockClient[] = [
  { id: "ana", nome: "Ana Paula Ribeiro", cpf: "284.519.678-09", telefone: "(16) 99128-4309", idade: "42 anos", sexo: "Feminino", estadoCivil: "Casada", profissao: "Empresária", renda: "R$ 10 mil a R$ 20 mil", cidade: "Ribeirão Preto, SP", escolaridade: "Superior completo", empreendimento: "Jardins do Vale", unidadeLote: "Q12 · Lote 18", quadra: "Q12", lote: "L18", area: "312 m²", valorUnidade: 186000, parcelasTotal: 60, parcelasLiquidadas: 39, parcelasVencidas: 3, parcelasAVencer: 18, saldoAtraso: 18450, atrasoDias: 38, scoreRisco: 82, prioridade: "Alta", responsavel: "Gustavo Freitas", status: "Em negociação", perfilParcela: "Parcela", vencimento: "2026-05-10", recuperado: 12200, segundaUnidade: { empreendimento: "Vista Alegre", unidadeLote: "Q12 · Lote 19", quadra: "Q12", lote: "L19", area: "308 m²", valorUnidade: 184000 } },
  { id: "carlos", nome: "Carlos Henrique Matos", cpf: "147.908.332-18", telefone: "(19) 98840-1203", idade: "49 anos", sexo: "Masculino", estadoCivil: "Divorciado", profissao: "Autônomo", renda: "R$ 5 mil a R$ 10 mil", cidade: "Campinas, SP", escolaridade: "Ensino médio", empreendimento: "Vista Alegre", unidadeLote: "Q07 · Lote 18", quadra: "Q07", lote: "L18", area: "450 m²", valorUnidade: 242000, parcelasTotal: 48, parcelasLiquidadas: 28, parcelasVencidas: 4, parcelasAVencer: 16, saldoAtraso: 32980, atrasoDias: 51, scoreRisco: 91, prioridade: "Crítica", responsavel: "Cinthia Cruz", status: "Escalado", perfilParcela: "Parcela", vencimento: "2026-04-10", recuperado: 8300 },
  { id: "mariana", nome: "Mariana Costa Lima", cpf: "602.441.019-77", telefone: "(41) 99821-7710", idade: "36 anos", sexo: "Feminino", estadoCivil: "Solteira", profissao: "CLT", renda: "R$ 5 mil a R$ 10 mil", cidade: "Curitiba, PR", escolaridade: "Superior completo", empreendimento: "Jardins do Vale", unidadeLote: "Q03 · Lote 04", quadra: "Q03", lote: "L04", area: "275 m²", valorUnidade: 154000, parcelasTotal: 48, parcelasLiquidadas: 31, parcelasVencidas: 2, parcelasAVencer: 15, saldoAtraso: 9210, atrasoDias: 24, scoreRisco: 64, prioridade: "Média", responsavel: "Gustavo Freitas", status: "Aguardando retorno", perfilParcela: "Sinal", vencimento: "2026-06-10", recuperado: 7600 },
  { id: "roberto", nome: "Roberto Nogueira", cpf: "733.120.554-02", telefone: "(17) 99710-2219", idade: "58 anos", sexo: "Masculino", estadoCivil: "Casado", profissao: "Servidor público", renda: "R$ 10 mil a R$ 20 mil", cidade: "São José do Rio Preto, SP", escolaridade: "Pós-graduação", empreendimento: "Reserva Alameda", unidadeLote: "Q02 · Lote 27", quadra: "Q02", lote: "L27", area: "520 m²", valorUnidade: 318000, parcelasTotal: 72, parcelasLiquidadas: 72, parcelasVencidas: 0, parcelasAVencer: 0, saldoAtraso: 0, atrasoDias: 0, scoreRisco: 42, prioridade: "Baixa", responsavel: "Cinthia Cruz", status: "Regularizado", perfilParcela: "Parcela", vencimento: "2026-07-10", recuperado: 18500 },
  { id: "patricia", nome: "Patrícia Amaral", cpf: "915.447.803-61", telefone: "(62) 99621-1184", idade: "51 anos", sexo: "Feminino", estadoCivil: "União estável", profissao: "Empresária", renda: "Acima de R$ 20 mil", cidade: "Goiânia, GO", escolaridade: "Superior completo", empreendimento: "Lavra do Ouro", unidadeLote: "Q09 · Lote 33", quadra: "Q09", lote: "L33", area: "410 m²", valorUnidade: 210000, parcelasTotal: 60, parcelasLiquidadas: 42, parcelasVencidas: 3, parcelasAVencer: 15, saldoAtraso: 22640, atrasoDias: 44, scoreRisco: 79, prioridade: "Alta", responsavel: "Gustavo Freitas", status: "Proposta enviada", perfilParcela: "Ato", vencimento: "2026-03-10", recuperado: 22200 },
  { id: "renato", nome: "Renato Pires", cpf: "381.044.920-15", telefone: "(62) 99218-4450", idade: "39 anos", sexo: "Masculino", estadoCivil: "Casado", profissao: "Autônomo", renda: "R$ 5 mil a R$ 10 mil", cidade: "Anápolis, GO", escolaridade: "Superior incompleto", empreendimento: "Vista Alegre", unidadeLote: "Q10 · Lote 02", quadra: "Q10", lote: "L02", area: "360 m²", valorUnidade: 198000, parcelasTotal: 60, parcelasLiquidadas: 34, parcelasVencidas: 5, parcelasAVencer: 21, saldoAtraso: 18700, atrasoDias: 92, scoreRisco: 88, prioridade: "Crítica", responsavel: "Cinthia Cruz", status: "Escalado", perfilParcela: "Parcela", vencimento: "2026-02-10", recuperado: 9200 },
  { id: "juliana", nome: "Juliana Castro", cpf: "720.118.664-90", telefone: "(64) 99801-2314", idade: "29 anos", sexo: "Feminino", estadoCivil: "Solteira", profissao: "CLT", renda: "Até R$ 5 mil", cidade: "Rio Verde, GO", escolaridade: "Superior incompleto", empreendimento: "Lavra do Ouro", unidadeLote: "Q04 · Lote 11", quadra: "Q04", lote: "L11", area: "290 m²", valorUnidade: 174000, parcelasTotal: 48, parcelasLiquidadas: 20, parcelasVencidas: 0, parcelasAVencer: 28, saldoAtraso: 0, atrasoDias: 0, scoreRisco: 36, prioridade: "Baixa", responsavel: "Gustavo Freitas", status: "A vencer", perfilParcela: "Sinal", vencimento: "2026-08-10", recuperado: 4800 },
  { id: "eduardo", nome: "Eduardo Martins", cpf: "118.775.402-36", telefone: "(11) 99721-8004", idade: "61 anos", sexo: "Masculino", estadoCivil: "Casado", profissao: "Servidor público", renda: "R$ 10 mil a R$ 20 mil", cidade: "Aparecida de Goiânia, GO", escolaridade: "Pós-graduação", empreendimento: "Reserva Alameda", unidadeLote: "Q15 · Lote 09", quadra: "Q15", lote: "L09", area: "480 m²", valorUnidade: 265000, parcelasTotal: 60, parcelasLiquidadas: 37, parcelasVencidas: 4, parcelasAVencer: 19, saldoAtraso: 28150, atrasoDias: 63, scoreRisco: 84, prioridade: "Alta", responsavel: "Cinthia Cruz", status: "Contato programado", perfilParcela: "Parcela", vencimento: "2026-05-20", recuperado: 14500 },
  { id: "fernanda", nome: "Fernanda Ruiz", cpf: "551.298.330-74", telefone: "(62) 99140-8819", idade: "44 anos", sexo: "Feminino", estadoCivil: "União estável", profissao: "CLT", renda: "R$ 10 mil a R$ 20 mil", cidade: "Goiânia, GO", escolaridade: "Superior completo", empreendimento: "Jardins do Vale", unidadeLote: "Q18 · Lote 21", quadra: "Q18", lote: "L21", area: "330 m²", valorUnidade: 226000, parcelasTotal: 60, parcelasLiquidadas: 60, parcelasVencidas: 0, parcelasAVencer: 0, saldoAtraso: 0, atrasoDias: 0, scoreRisco: 28, prioridade: "Baixa", responsavel: "Gustavo Freitas", status: "Regularizado", perfilParcela: "Parcela", vencimento: "2026-01-10", recuperado: 11300 },
  { id: "marcelo", nome: "Marcelo Duarte", cpf: "411.883.291-02", telefone: "(62) 99533-4431", idade: "27 anos", sexo: "Masculino", estadoCivil: "Solteiro", profissao: "Autônomo", renda: "Até R$ 5 mil", cidade: "Anápolis, GO", escolaridade: "Ensino médio", empreendimento: "Vista Alegre", unidadeLote: "Q06 · Lote 15", quadra: "Q06", lote: "L15", area: "300 m²", valorUnidade: 152000, parcelasTotal: 48, parcelasLiquidadas: 22, parcelasVencidas: 2, parcelasAVencer: 24, saldoAtraso: 11800, atrasoDias: 14, scoreRisco: 58, prioridade: "Média", responsavel: "Cinthia Cruz", status: "Contato programado", perfilParcela: "Ato", vencimento: "2026-05-05", recuperado: 4200 },
  { id: "cintia", nome: "Cíntia Rocha", cpf: "993.210.446-17", telefone: "(64) 99918-0210", idade: "41 anos", sexo: "Feminino", estadoCivil: "Divorciada", profissao: "Servidor público", renda: "R$ 5 mil a R$ 10 mil", cidade: "Rio Verde, GO", escolaridade: "Superior completo", empreendimento: "Lavra do Ouro", unidadeLote: "Q11 · Lote 08", quadra: "Q11", lote: "L08", area: "365 m²", valorUnidade: 246000, parcelasTotal: 60, parcelasLiquidadas: 38, parcelasVencidas: 3, parcelasAVencer: 19, saldoAtraso: 19400, atrasoDias: 29, scoreRisco: 73, prioridade: "Alta", responsavel: "Gustavo Freitas", status: "Em negociação", perfilParcela: "Parcela", vencimento: "2026-04-25", recuperado: 8900 },
  { id: "paulo", nome: "Paulo Henrique", cpf: "204.661.900-55", telefone: "(62) 99102-5509", idade: "52 anos", sexo: "Masculino", estadoCivil: "Casado", profissao: "CLT", renda: "R$ 5 mil a R$ 10 mil", cidade: "Aparecida de Goiânia, GO", escolaridade: "Ensino médio", empreendimento: "Reserva Alameda", unidadeLote: "Q01 · Lote 03", quadra: "Q01", lote: "L03", area: "315 m²", valorUnidade: 169000, parcelasTotal: 48, parcelasLiquidadas: 18, parcelasVencidas: 0, parcelasAVencer: 30, saldoAtraso: 0, atrasoDias: 0, scoreRisco: 31, prioridade: "Baixa", responsavel: "Cinthia Cruz", status: "A vencer", perfilParcela: "Sinal", vencimento: "2026-09-10", recuperado: 6900 },
  { id: "helena", nome: "Helena Moura", cpf: "617.442.890-31", telefone: "(62) 99877-1102", idade: "34 anos", sexo: "Feminino", estadoCivil: "Casada", profissao: "Empresária", renda: "R$ 10 mil a R$ 20 mil", cidade: "Luziânia, GO", escolaridade: "Superior completo", empreendimento: "Lagoa Bonita", unidadeLote: "Q05 · Lote 12", quadra: "Q05", lote: "L12", area: "380 m²", valorUnidade: 205000, parcelasTotal: 60, parcelasLiquidadas: 36, parcelasVencidas: 2, parcelasAVencer: 22, saldoAtraso: 14300, atrasoDias: 22, scoreRisco: 69, prioridade: "Média", responsavel: "Gustavo Freitas", status: "Aguardando retorno", perfilParcela: "Parcela", vencimento: "2026-06-05", recuperado: 7200 },
  { id: "bruno", nome: "Bruno Azevedo", cpf: "845.109.775-40", telefone: "(61) 99201-3477", idade: "46 anos", sexo: "Masculino", estadoCivil: "Casado", profissao: "Autônomo", renda: "R$ 5 mil a R$ 10 mil", cidade: "Brasília, DF", escolaridade: "Superior incompleto", empreendimento: "Lagoa Bonita", unidadeLote: "Q08 · Lote 04", quadra: "Q08", lote: "L04", area: "405 m²", valorUnidade: 232000, parcelasTotal: 60, parcelasLiquidadas: 31, parcelasVencidas: 5, parcelasAVencer: 24, saldoAtraso: 35600, atrasoDias: 76, scoreRisco: 89, prioridade: "Crítica", responsavel: "Cinthia Cruz", status: "Escalado", perfilParcela: "Parcela", vencimento: "2026-03-18", recuperado: 5100 },
  { id: "larissa", nome: "Larissa Gomes", cpf: "733.518.009-62", telefone: "(62) 99982-0117", idade: "31 anos", sexo: "Feminino", estadoCivil: "Solteira", profissao: "CLT", renda: "Até R$ 5 mil", cidade: "Trindade, GO", escolaridade: "Superior completo", empreendimento: "Morada da Serra", unidadeLote: "Q02 · Lote 17", quadra: "Q02", lote: "L17", area: "285 m²", valorUnidade: 158000, parcelasTotal: 48, parcelasLiquidadas: 26, parcelasVencidas: 1, parcelasAVencer: 21, saldoAtraso: 5200, atrasoDias: 9, scoreRisco: 45, prioridade: "Baixa", responsavel: "Gustavo Freitas", status: "Contato programado", perfilParcela: "Sinal", vencimento: "2026-06-22", recuperado: 3100 },
  { id: "rodrigo", nome: "Rodrigo Sampaio", cpf: "470.221.380-80", telefone: "(62) 99441-0887", idade: "38 anos", sexo: "Masculino", estadoCivil: "União estável", profissao: "Empresário", renda: "Acima de R$ 20 mil", cidade: "Goiânia, GO", escolaridade: "Pós-graduação", empreendimento: "Morada da Serra", unidadeLote: "Q09 · Lote 26", quadra: "Q09", lote: "L26", area: "510 m²", valorUnidade: 298000, parcelasTotal: 72, parcelasLiquidadas: 43, parcelasVencidas: 3, parcelasAVencer: 26, saldoAtraso: 27400, atrasoDias: 41, scoreRisco: 76, prioridade: "Alta", responsavel: "Cinthia Cruz", status: "Proposta enviada", perfilParcela: "Ato", vencimento: "2026-04-30", recuperado: 16700, segundaUnidade: { empreendimento: "Lagoa Bonita", unidadeLote: "Q01 · Lote 09", quadra: "Q01", lote: "L09", area: "340 m²", valorUnidade: 188000 } },
  { id: "debora", nome: "Débora Nunes", cpf: "590.334.771-29", telefone: "(94) 99172-0041", idade: "45 anos", sexo: "Feminino", estadoCivil: "Divorciada", profissao: "Servidor público", renda: "R$ 10 mil a R$ 20 mil", cidade: "Belém, PA", escolaridade: "Superior completo", empreendimento: "Recanto do Pará", unidadeLote: "Q14 · Lote 07", quadra: "Q14", lote: "L07", area: "390 m²", valorUnidade: 221000, parcelasTotal: 60, parcelasLiquidadas: 40, parcelasVencidas: 2, parcelasAVencer: 18, saldoAtraso: 13200, atrasoDias: 19, scoreRisco: 62, prioridade: "Média", responsavel: "Gustavo Freitas", status: "Em negociação", perfilParcela: "Parcela", vencimento: "2026-05-28", recuperado: 9800 },
  { id: "mateus", nome: "Mateus Oliveira", cpf: "188.602.447-93", telefone: "(91) 99801-7782", idade: "33 anos", sexo: "Masculino", estadoCivil: "Solteiro", profissao: "Autônomo", renda: "R$ 5 mil a R$ 10 mil", cidade: "Ananindeua, PA", escolaridade: "Ensino médio", empreendimento: "Recanto do Pará", unidadeLote: "Q06 · Lote 20", quadra: "Q06", lote: "L20", area: "350 m²", valorUnidade: 176000, parcelasTotal: 48, parcelasLiquidadas: 21, parcelasVencidas: 4, parcelasAVencer: 23, saldoAtraso: 21800, atrasoDias: 67, scoreRisco: 86, prioridade: "Crítica", responsavel: "Cinthia Cruz", status: "Escalado", perfilParcela: "Parcela", vencimento: "2026-03-25", recuperado: 2400 },
  { id: "simone", nome: "Simone Batista", cpf: "340.772.118-54", telefone: "(91) 99283-3310", idade: "56 anos", sexo: "Feminino", estadoCivil: "Casada", profissao: "CLT", renda: "R$ 5 mil a R$ 10 mil", cidade: "Castanhal, PA", escolaridade: "Superior incompleto", empreendimento: "Recanto do Pará", unidadeLote: "Q03 · Lote 14", quadra: "Q03", lote: "L14", area: "310 m²", valorUnidade: 164000, parcelasTotal: 48, parcelasLiquidadas: 28, parcelasVencidas: 0, parcelasAVencer: 20, saldoAtraso: 0, atrasoDias: 0, scoreRisco: 39, prioridade: "Baixa", responsavel: "Gustavo Freitas", status: "A vencer", perfilParcela: "Sinal", vencimento: "2026-08-18", recuperado: 5600 },
  { id: "fabio", nome: "Fábio Albuquerque", cpf: "699.118.320-73", telefone: "(62) 99542-7061", idade: "48 anos", sexo: "Masculino", estadoCivil: "Casado", profissao: "Empresário", renda: "Acima de R$ 20 mil", cidade: "Goiânia, GO", escolaridade: "Superior completo", empreendimento: "Lagoa Bonita", unidadeLote: "Q11 · Lote 02", quadra: "Q11", lote: "L02", area: "455 m²", valorUnidade: 286000, parcelasTotal: 72, parcelasLiquidadas: 46, parcelasVencidas: 2, parcelasAVencer: 24, saldoAtraso: 17600, atrasoDias: 33, scoreRisco: 71, prioridade: "Alta", responsavel: "Gustavo Freitas", status: "Proposta enviada", perfilParcela: "Ato", vencimento: "2026-05-12", recuperado: 19600 },
  { id: "aline", nome: "Aline Teixeira", cpf: "828.451.909-08", telefone: "(62) 99831-4420", idade: "37 anos", sexo: "Feminino", estadoCivil: "Solteira", profissao: "CLT", renda: "R$ 5 mil a R$ 10 mil", cidade: "Senador Canedo, GO", escolaridade: "Superior completo", empreendimento: "Morada da Serra", unidadeLote: "Q04 · Lote 06", quadra: "Q04", lote: "L06", area: "295 m²", valorUnidade: 172000, parcelasTotal: 48, parcelasLiquidadas: 29, parcelasVencidas: 2, parcelasAVencer: 17, saldoAtraso: 8800, atrasoDias: 27, scoreRisco: 60, prioridade: "Média", responsavel: "Cinthia Cruz", status: "Aguardando retorno", perfilParcela: "Parcela", vencimento: "2026-06-02", recuperado: 4300 },
  { id: "victor", nome: "Victor Hugo Ramos", cpf: "501.220.781-90", telefone: "(62) 99117-0921", idade: "43 anos", sexo: "Masculino", estadoCivil: "Divorciado", profissao: "Autônomo", renda: "Até R$ 5 mil", cidade: "Anápolis, GO", escolaridade: "Ensino médio", empreendimento: "Vista Alegre", unidadeLote: "Q13 · Lote 10", quadra: "Q13", lote: "L10", area: "320 m²", valorUnidade: 181000, parcelasTotal: 48, parcelasLiquidadas: 19, parcelasVencidas: 4, parcelasAVencer: 25, saldoAtraso: 24400, atrasoDias: 58, scoreRisco: 83, prioridade: "Alta", responsavel: "Cinthia Cruz", status: "Contato programado", perfilParcela: "Parcela", vencimento: "2026-04-18", recuperado: 3600 },
  { id: "monica", nome: "Mônica Farias", cpf: "210.765.990-44", telefone: "(64) 99631-2208", idade: "50 anos", sexo: "Feminino", estadoCivil: "Casada", profissao: "Servidor público", renda: "R$ 10 mil a R$ 20 mil", cidade: "Rio Verde, GO", escolaridade: "Pós-graduação", empreendimento: "Lavra do Ouro", unidadeLote: "Q16 · Lote 25", quadra: "Q16", lote: "L25", area: "470 m²", valorUnidade: 274000, parcelasTotal: 72, parcelasLiquidadas: 50, parcelasVencidas: 1, parcelasAVencer: 21, saldoAtraso: 7600, atrasoDias: 12, scoreRisco: 49, prioridade: "Baixa", responsavel: "Gustavo Freitas", status: "Em negociação", perfilParcela: "Ato", vencimento: "2026-07-02", recuperado: 10200 },
  { id: "sergio", nome: "Sérgio Lima", cpf: "190.331.778-65", telefone: "(62) 99340-4451", idade: "54 anos", sexo: "Masculino", estadoCivil: "Casado", profissao: "Transportador autônomo", renda: "R$ 5 mil a R$ 10 mil", cidade: "Aparecida de Goiânia, GO", escolaridade: "Ensino médio", empreendimento: "Reserva Alameda", unidadeLote: "Q08 · Lote 31", quadra: "Q08", lote: "L31", area: "405 m²", valorUnidade: 238000, parcelasTotal: 60, parcelasLiquidadas: 33, parcelasVencidas: 5, parcelasAVencer: 22, saldoAtraso: 30400, atrasoDias: 88, scoreRisco: 90, prioridade: "Crítica", responsavel: "Cinthia Cruz", status: "Escalado", perfilParcela: "Parcela", vencimento: "2026-03-12", recuperado: 1900 },
  { id: "beatriz", nome: "Beatriz Carvalho", cpf: "864.553.109-27", telefone: "(62) 99774-2218", idade: "28 anos", sexo: "Feminino", estadoCivil: "Solteira", profissao: "CLT", renda: "Até R$ 5 mil", cidade: "Goiânia, GO", escolaridade: "Superior incompleto", empreendimento: "Jardins do Vale", unidadeLote: "Q21 · Lote 05", quadra: "Q21", lote: "L05", area: "260 m²", valorUnidade: 149000, parcelasTotal: 48, parcelasLiquidadas: 16, parcelasVencidas: 1, parcelasAVencer: 31, saldoAtraso: 3900, atrasoDias: 6, scoreRisco: 37, prioridade: "Baixa", responsavel: "Gustavo Freitas", status: "Contato programado", perfilParcela: "Sinal", vencimento: "2026-07-18", recuperado: 2100 },
  { id: "daniel", nome: "Daniel Ferreira", cpf: "335.900.770-11", telefone: "(62) 99408-7732", idade: "35 anos", sexo: "Masculino", estadoCivil: "União estável", profissao: "Empresário", renda: "R$ 10 mil a R$ 20 mil", cidade: "Trindade, GO", escolaridade: "Superior completo", empreendimento: "Morada da Serra", unidadeLote: "Q12 · Lote 18", quadra: "Q12", lote: "L18", area: "375 m²", valorUnidade: 219000, parcelasTotal: 60, parcelasLiquidadas: 35, parcelasVencidas: 3, parcelasAVencer: 22, saldoAtraso: 16800, atrasoDias: 35, scoreRisco: 74, prioridade: "Alta", responsavel: "Cinthia Cruz", status: "Proposta enviada", perfilParcela: "Parcela", vencimento: "2026-05-22", recuperado: 11800 },
  { id: "thais", nome: "Thaís Moreira", cpf: "420.661.228-72", telefone: "(91) 99331-7780", idade: "40 anos", sexo: "Feminino", estadoCivil: "Casada", profissao: "Autônoma", renda: "R$ 5 mil a R$ 10 mil", cidade: "Belém, PA", escolaridade: "Superior completo", empreendimento: "Recanto do Pará", unidadeLote: "Q18 · Lote 22", quadra: "Q18", lote: "L22", area: "420 m²", valorUnidade: 241000, parcelasTotal: 60, parcelasLiquidadas: 32, parcelasVencidas: 4, parcelasAVencer: 24, saldoAtraso: 26300, atrasoDias: 73, scoreRisco: 87, prioridade: "Crítica", responsavel: "Cinthia Cruz", status: "Escalado", perfilParcela: "Parcela", vencimento: "2026-04-02", recuperado: 3400 },
];
