export const cssVariables = {
  colors: {
    brandPrimary: "--uix-color-brand-primary",
    brandForeground: "--uix-color-brand-foreground",
    focus: "--uix-color-focus",
    success: "--uix-color-success",
    warning: "--uix-color-warning",
    danger: "--uix-color-danger",
  },
  surfaces: {
    canvas: "--uix-surface-canvas",
    base: "--uix-surface-base",
    raised: "--uix-surface-raised",
    subtle: "--uix-surface-subtle",
    inverse: "--uix-surface-inverse",
  },
  text: {
    primary: "--uix-text-primary",
    secondary: "--uix-text-secondary",
    muted: "--uix-text-muted",
  },
  borders: {
    subtle: "--uix-border-subtle",
    strong: "--uix-border-strong",
  },
  typography: {
    fontSans: "--uix-font-sans",
    fontMono: "--uix-font-mono",
    fontSizeXs: "--uix-font-size-xs",
    fontSizeSm: "--uix-font-size-sm",
    fontSizeMd: "--uix-font-size-md",
    fontSizeLg: "--uix-font-size-lg",
    fontSizeXl: "--uix-font-size-xl",
    fontSize2xl: "--uix-font-size-2xl",
  },
  spacing: {
    0: "--uix-space-0",
    1: "--uix-space-1",
    2: "--uix-space-2",
    3: "--uix-space-3",
    4: "--uix-space-4",
    5: "--uix-space-5",
    6: "--uix-space-6",
    8: "--uix-space-8",
    10: "--uix-space-10",
    12: "--uix-space-12",
    16: "--uix-space-16",
    20: "--uix-space-20",
    24: "--uix-space-24",
  },
  radius: {
    none: "--uix-radius-none",
    xs: "--uix-radius-xs",
    sm: "--uix-radius-sm",
    md: "--uix-radius-md",
    lg: "--uix-radius-lg",
    full: "--uix-radius-full",
  },
  shadows: {
    none: "--uix-shadow-none",
    xs: "--uix-shadow-xs",
    sm: "--uix-shadow-sm",
    md: "--uix-shadow-md",
  },
  zIndex: {
    base: "--uix-z-base",
    raised: "--uix-z-raised",
    sticky: "--uix-z-sticky",
    overlay: "--uix-z-overlay",
    modal: "--uix-z-modal",
    toast: "--uix-z-toast",
  },
  density: {
    controlHeight: "--uix-density-control-height",
    gap: "--uix-density-gap",
    paddingX: "--uix-density-padding-x",
    paddingY: "--uix-density-padding-y",
  },
} as const;

export type CssVariables = typeof cssVariables;
