import type {
  PulseXCallSession,
  PulseXChannel,
  PulseXFutureCapability,
  PulseXMessage,
  PulseXMessageTag,
  PulseXPresenceUser,
  PulseXReactionEmoji,
  PulseXThreadReply,
} from "./types";

function applyPresenceRule(
  users: readonly PulseXPresenceUser[],
): PulseXPresenceUser[] {
  return users.map((user) => {
    if (
      user.status === "online" &&
      typeof user.lastInteractionMinutesAgo === "number" &&
      user.lastInteractionMinutesAgo > 20
    ) {
      return {
        ...user,
        status: "away",
      };
    }

    return { ...user };
  });
}

function applyMentionPendingRule(
  messages: readonly PulseXMessage[],
): PulseXMessage[] {
  return messages.map((message) => {
    const hasExpiredMention =
      (message.mentionUserIds?.length ?? 0) > 0 &&
      (message.mentionAgeMinutes ?? 0) >= 60 &&
      !message.mentionRespondedAt;

    if (!hasExpiredMention) {
      return { ...message };
    }

    return {
      ...message,
      status: "warning",
      tags: [
        ...new Set<PulseXMessageTag>([...(message.tags ?? []), "pendente"]),
      ],
    };
  });
}

export const pulsexChannels = [
  {
    avatar: "CB",
    context: {
      filesCount: 8,
      owner: "Nívea Careli",
      priority: "alta",
      status: "Em andamento",
      unit: "Operacao",
    },
    description: "Comunicacao operacional da cobranca Careli.",
    id: "cobranca",
    kind: "operations",
    lastMessageAt: "09:24",
    name: "Cobranca",
    preview: "Desk confirmou retorno dos acordos...",
    status: "online",
    unreadCount: 3,
  },
  {
    avatar: "DK",
    context: {
      filesCount: 4,
      owner: "Gustavo Freitas",
      priority: "media",
      status: "Acompanhamento",
      unit: "Operacao",
    },
    description: "Fila de atendimento operacional do Desk.",
    id: "desk",
    kind: "operations",
    lastMessageAt: "09:21",
    name: "Desk",
    preview: "Priorizar retornos pendentes ate 11h.",
    status: "online",
    unreadCount: 1,
  },
  {
    avatar: "WF",
    context: {
      filesCount: 5,
      owner: "Lucas Ruas",
      priority: "media",
      status: "Alinhamento",
      unit: "Operacao",
    },
    description: "Fluxos, rotinas e automacoes operacionais.",
    id: "workflow",
    kind: "operations",
    lastMessageAt: "09:20",
    name: "Workflow",
    preview: "Quando Financeiro entrar, precisamos...",
    status: "away",
  },
  {
    avatar: "FI",
    context: {
      filesCount: 7,
      owner: "Gustavo Freitas",
      status: "Fechamento",
      unit: "Operacao",
    },
    description: "Financeiro, repasses e fechamento operacional.",
    id: "financeiro",
    kind: "operations",
    lastMessageAt: "09:02",
    name: "Financeiro",
    preview: "Nívea Careli aprovou os repasses do dia.",
    status: "away",
    unreadCount: 1,
  },
  {
    avatar: "GD",
    context: {
      filesCount: 6,
      owner: "Lucas Ruas",
      status: "Monitoramento",
      unit: "Tecnologia",
    },
    description: "Canal tecnico do Guardian.",
    id: "guardian",
    kind: "technology",
    lastMessageAt: "09:28",
    name: "Guardian",
    preview: "Monitoramento do dashboard voltou ao normal.",
    status: "online",
  },
  {
    avatar: "PX",
    context: {
      filesCount: 2,
      owner: "Lucas Ruas",
      status: "Produto",
      unit: "Tecnologia",
    },
    description: "Canal de evolucao do PulseX.",
    id: "pulsex",
    kind: "technology",
    lastMessageAt: "09:16",
    name: "PulseX",
    preview: "Composer segue mockado por enquanto.",
    status: "online",
  },
  {
    avatar: "IN",
    context: {
      filesCount: 1,
      owner: "Gustavo Freitas",
      status: "Disponivel",
      unit: "Tecnologia",
    },
    description: "Infraestrutura, acessos e monitoramento tecnico.",
    id: "infraestrutura",
    kind: "technology",
    lastMessageAt: "08:52",
    name: "Infraestrutura",
    preview: "Ambiente estavel para os modulos internos.",
    status: "offline",
  },
  {
    avatar: "AT",
    context: {
      filesCount: 3,
      owner: "Catherine Faria",
      status: "Ativo",
      unit: "Relacao",
    },
    description: "Atendimento e acompanhamento de relacionamento.",
    id: "atendimento",
    kind: "relation",
    lastMessageAt: "09:12",
    name: "Atendimento",
    preview: "Retornos da manha foram distribuidos.",
    status: "online",
  },
  {
    avatar: "CM",
    context: {
      filesCount: 2,
      owner: "Nívea Careli",
      status: "Ativo",
      unit: "Relacao",
    },
    description: "Comercial, prospeccao e relacionamento institucional.",
    id: "comercial",
    kind: "relation",
    lastMessageAt: "08:47",
    name: "Comercial",
    preview: "Enviar resumo antes da reuniao.",
    status: "away",
  },
  {
    avatar: "DR",
    context: {
      filesCount: 4,
      owner: "Nívea Careli",
      status: "Alinhamento",
      unit: "Relacao",
    },
    description: "Diretoria, alinhamentos e decisoes executivas.",
    id: "diretoria",
    kind: "relation",
    lastMessageAt: "08:35",
    name: "Diretoria",
    preview: "Follow-up executivo marcado para 10h30.",
    status: "busy",
  },
  {
    avatar: "NC",
    context: {
      filesCount: 0,
      owner: "Nívea Careli",
      status: "Direta",
      unit: "Diretas",
    },
    description: "Conversa direta com Nívea Careli.",
    id: "nivea-careli",
    kind: "direct",
    lastMessageAt: "09:31",
    name: "Nívea Careli",
    preview: "Me chama quando fechar a pauta.",
    status: "online",
    unreadCount: 2,
  },
  {
    avatar: "GF",
    context: {
      filesCount: 0,
      owner: "Gustavo Freitas",
      status: "Direta",
      unit: "Diretas",
    },
    description: "Conversa direta com Gustavo Freitas.",
    id: "gustavo-freitas",
    kind: "direct",
    lastMessageAt: "09:05",
    name: "Gustavo Freitas",
    preview: "Subi o ajuste para revisar.",
    status: "online",
  },
  {
    avatar: "CF",
    context: {
      filesCount: 0,
      owner: "Catherine Faria",
      status: "Direta",
      unit: "Diretas",
    },
    description: "Conversa direta com Catherine Faria.",
    id: "catherine-faria",
    kind: "direct",
    lastMessageAt: "08:59",
    name: "Catherine Faria",
    preview: "Atendimento alinhado para hoje.",
    status: "busy",
  },
  {
    avatar: "LR",
    context: {
      filesCount: 0,
      owner: "Lucas Ruas",
      status: "Direta",
      unit: "Diretas",
    },
    description: "Conversa direta com Lucas Ruas.",
    id: "lucas-ruas",
    kind: "direct",
    lastMessageAt: "08:40",
    name: "Lucas Ruas",
    preview: "Vou ajustar o shell operacional.",
    status: "away",
  },
] as const satisfies readonly PulseXChannel[];

export const pulsexPresenceUsers = applyPresenceRule([
  {
    channelIds: [
      "cobranca",
      "desk",
      "workflow",
      "financeiro",
      "atendimento",
      "diretoria",
    ],
    id: "ana",
    initials: "NC",
    email: "nivea@careli.com",
    label: "Nívea Careli",
    lastInteractionMinutesAgo: 3,
    role: "Operacao",
    status: "online",
    username: "nivea",
  },
  {
    channelIds: ["guardian", "pulsex", "infraestrutura", "workflow", "lucas-ruas"],
    id: "leo",
    initials: "LR",
    email: "lucas@careli.com",
    label: "Lucas Ruas",
    lastInteractionMinutesAgo: 27,
    role: "Tecnologia",
    status: "online",
    username: "lucas",
  },
  {
    channelIds: ["cobranca", "desk", "financeiro", "comercial", "gustavo-freitas"],
    id: "mia",
    initials: "GF",
    email: "gustavo@careli.com",
    label: "Gustavo Freitas",
    lastInteractionMinutesAgo: 8,
    role: "Operacao",
    status: "busy",
    username: "gustavo",
  },
  {
    channelIds: ["atendimento", "comercial", "diretoria", "catherine-faria"],
    id: "rui",
    initials: "CF",
    email: "catherine@careli.com",
    label: "Catherine Faria",
    lastInteractionMinutesAgo: 46,
    role: "Relacao",
    status: "away",
    username: "catherine",
  },
] as const satisfies readonly PulseXPresenceUser[]);

export const pulsexMessages = applyMentionPendingRule([
  {
    authorId: "ana",
    body: "Gustavo Freitas precisamos confirmar retorno dos acordos acima de 15 dias antes das 10h.",
    channelId: "cobranca",
    deliveredTo: ["leo", "mia", "rui"],
    id: "msg-001",
    lastThreadReplyAt: "09:18",
    mentionAgeMinutes: 82,
    mentionUserIds: ["mia"],
    mentions: [
      {
        displayName: "Gustavo Freitas",
        trigger: "@gustavo",
        userId: "mia",
      },
    ],
    readBy: ["leo"],
    reactions: [
      {
        count: 2,
        emoji: "👀",
        reactedByUserIds: ["leo", "rui"],
      },
    ],
    status: "info",
    tags: ["urgente", "acompanhar"],
    threadCount: 2,
    timestamp: "08:18",
  },
  {
    authorId: "mia",
    body: "Respondido: acordos revisados, vou subir o resumo no financeiro ainda de manha.",
    channelId: "cobranca",
    deliveredTo: ["ana", "leo"],
    id: "msg-002",
    mentionRespondedAt: "09:17",
    readBy: ["ana"],
    reactions: [
      {
        count: 2,
        emoji: "✅",
        reactedByUserIds: ["ana", "leo"],
      },
    ],
    status: "success",
    tags: ["resolvido"],
    threadCount: 0,
    timestamp: "09:17",
  },
  {
    authorId: "rui",
    attachment: {
      label: "fila-desk-09h.pdf",
      type: "file",
    },
    body: "Nívea Careli fila do Desk com 12 retornos pendentes. Priorizei os casos urgentes.",
    channelId: "desk",
    deliveredTo: ["ana", "mia"],
    id: "msg-003",
    mentionAgeMinutes: 34,
    mentionUserIds: ["ana"],
    mentions: [
      {
        displayName: "Nívea Careli",
        trigger: "@nivea",
        userId: "ana",
      },
    ],
    readBy: ["ana"],
    status: "warning",
    tags: ["pendente", "importante"],
    threadCount: 1,
    timestamp: "09:21",
  },
  {
    authorId: "leo",
    body: "Guardian voltou a sincronizar. Monitoramento ficou verde desde 09:26.",
    channelId: "guardian",
    deliveredTo: ["ana", "rui"],
    id: "msg-004",
    readBy: ["ana", "rui"],
    reactions: [
      {
        count: 3,
        emoji: "✅",
        reactedByUserIds: ["ana", "mia", "rui"],
      },
    ],
    status: "success",
    tags: ["resolvido"],
    threadCount: 0,
    timestamp: "09:28",
  },
  {
    authorId: "leo",
    body: "Preparei o contrato para threads, reactions e tags sem acoplar backend. Composer segue mockado.",
    channelId: "pulsex",
    deliveredTo: ["ana", "mia"],
    id: "msg-005",
    readBy: ["ana"],
    reactions: [
      {
        count: 2,
        emoji: "👀",
        reactedByUserIds: ["ana", "mia"],
      },
    ],
    status: "info",
    tags: ["importante"],
    threadCount: 1,
    timestamp: "09:16",
  },
  {
    authorId: "mia",
    body: "Lucas Ruas quando Financeiro entrar, precisamos de alertas por modulo e mencoes pendentes.",
    channelId: "workflow",
    deliveredTo: ["ana", "leo"],
    id: "msg-006",
    mentionAgeMinutes: 96,
    mentionUserIds: ["leo"],
    mentions: [
      {
        displayName: "Lucas Ruas",
        trigger: "@lucas",
        userId: "leo",
      },
    ],
    readBy: ["ana"],
    reactions: [
      {
        count: 1,
        emoji: "🚀",
        reactedByUserIds: ["ana"],
      },
    ],
    status: "info",
    tags: ["acompanhar"],
    threadCount: 0,
    timestamp: "07:58",
  },
  {
    authorId: "ana",
    body: "Financeiro aprovado. Gustavo Freitas pode seguir com repasses do lote B.",
    channelId: "financeiro",
    deliveredTo: ["mia", "leo"],
    id: "msg-007",
    mentionAgeMinutes: 18,
    mentionUserIds: ["mia"],
    mentions: [
      {
        displayName: "Gustavo Freitas",
        trigger: "@gustavo",
        userId: "mia",
      },
    ],
    readBy: ["mia"],
    status: "success",
    tags: ["importante"],
    threadCount: 0,
    timestamp: "09:02",
  },
  {
    authorId: "rui",
    body: "Atendimento alinhado. Clientes sensiveis ficam em follow-up ate o fim do dia.",
    channelId: "atendimento",
    deliveredTo: ["ana"],
    id: "msg-008",
    readBy: ["ana"],
    status: "neutral",
    tags: ["acompanhar"],
    threadCount: 0,
    timestamp: "09:12",
  },
  {
    authorId: "ana",
    body: "Diretoria: manter pauta objetiva, com status de cobranca, financeiro e Guardian.",
    channelId: "diretoria",
    deliveredTo: ["rui", "mia"],
    id: "msg-009",
    readBy: ["rui"],
    status: "info",
    tags: ["importante"],
    threadCount: 0,
    timestamp: "08:35",
  },
  {
    authorId: "mia",
    body: "Infraestrutura segue estavel. Sem incidentes desde a troca do token.",
    channelId: "infraestrutura",
    deliveredTo: ["leo"],
    id: "msg-010",
    readBy: [],
    status: "success",
    tags: ["resolvido"],
    threadCount: 0,
    timestamp: "08:52",
  },
] as const satisfies readonly PulseXMessage[]);

export const pulsexReactionOptions = [
  "👍",
  "✅",
  "👀",
  "🚀",
] as const satisfies readonly PulseXReactionEmoji[];

export const pulsexThreadReplies = {
  "msg-001": [
    {
      authorId: "leo",
      body: "Boa. Esse canal pode virar a linha do tempo operacional do Guardian.",
      id: "reply-001",
      messageId: "msg-001",
      timestamp: "09:14",
    },
    {
      authorId: "mia",
      body: "Tambem quero filtrar por modulo quando o backend entrar.",
      id: "reply-002",
      messageId: "msg-001",
      timestamp: "09:18",
    },
  ],
  "msg-005": [
    {
      authorId: "ana",
      body: "Perfeito. Primeiro local, depois contrato realtime.",
      id: "reply-003",
      messageId: "msg-005",
      timestamp: "09:19",
    },
  ],
} as const satisfies Record<string, readonly PulseXThreadReply[]>;

export const pulsexActivityEvents = [
  {
    description: "Mencoes sem resposta ha mais de 1 hora recebem tag pendente.",
    id: "activity-pending-mention",
    status: "warning",
    timestamp: "agora",
    title: "Mencao pendente aplicada",
    type: "automation",
  },
  {
    description: "Usuarios online ha mais de 20 min sem interacao viram ausentes.",
    id: "activity-presence-rule",
    status: "processing",
    timestamp: "2 min",
    title: "Presenca recalculada",
    type: "presence",
  },
  {
    description: "Threads, reactions, mentions, tags e leitura seguem como contratos futuros.",
    id: "activity-roadmap",
    status: "info",
    timestamp: "5 min",
    title: "Camadas futuras reservadas",
    type: "roadmap",
  },
] as const;

export const pulsexFutureCapabilities = [
  "threads",
  "reactions",
  "mentions",
  "uploads",
  "calls",
  "ai-assistant",
] as const satisfies readonly PulseXFutureCapability[];

export const pulsexCallSessions = [
  {
    channelId: "cobranca",
    durationLabel: "12:08",
    id: "call-active-cobranca",
    initiatedByUserId: "ana",
    participants: [
      {
        id: "call-participant-ana",
        initials: "NC",
        isCameraOn: true,
        isMuted: false,
        label: "Nivea Careli",
        presenceStatus: "online",
        role: "Operacao",
        status: "joined",
        userId: "ana",
      },
      {
        id: "call-participant-mia",
        initials: "GF",
        isCameraOn: false,
        isMuted: true,
        label: "Gustavo Freitas",
        presenceStatus: "busy",
        role: "Operacao",
        status: "muted",
        userId: "mia",
      },
      {
        id: "call-participant-leo",
        initials: "LR",
        isCameraOn: true,
        isMuted: false,
        label: "Lucas Ruas",
        presenceStatus: "away",
        role: "Tecnologia",
        status: "joined",
        userId: "leo",
      },
    ],
    startedAt: "09:18",
    status: "active",
    title: "Alinhamento de cobranca",
    type: "video",
  },
  {
    channelId: "diretoria",
    durationLabel: "00:00",
    endedAt: "08:42",
    id: "call-missed-diretoria",
    initiatedByUserId: "ana",
    participants: [
      {
        id: "call-participant-rui-missed",
        initials: "CF",
        isCameraOn: false,
        isMuted: false,
        label: "Catherine Faria",
        presenceStatus: "away",
        role: "Relacao",
        status: "invited",
        userId: "rui",
      },
    ],
    startedAt: "08:40",
    status: "missed",
    title: "Chamada perdida da diretoria",
    type: "audio",
  },
  {
    channelId: "guardian",
    durationLabel: "18:32",
    endedAt: "09:04",
    id: "call-ended-guardian",
    initiatedByUserId: "leo",
    participants: [
      {
        id: "call-participant-leo-ended",
        initials: "LR",
        isCameraOn: true,
        isMuted: false,
        label: "Lucas Ruas",
        presenceStatus: "away",
        role: "Tecnologia",
        status: "left",
        userId: "leo",
      },
      {
        id: "call-participant-ana-ended",
        initials: "NC",
        isCameraOn: false,
        isMuted: false,
        label: "Nivea Careli",
        presenceStatus: "online",
        role: "Operacao",
        status: "left",
        userId: "ana",
      },
    ],
    startedAt: "08:45",
    status: "ended",
    title: "Validacao Guardian",
    type: "video",
  },
  {
    channelId: "cobranca",
    durationLabel: "tocando",
    id: "call-ringing-cobranca",
    initiatedByUserId: "mia",
    participants: [
      {
        avatarUrl: "https://i.pravatar.cc/128?img=12",
        id: "call-participant-mia-ringing",
        initials: "GF",
        isCameraOn: false,
        isMuted: false,
        label: "Gustavo Freitas",
        presenceStatus: "busy",
        role: "Operacao",
        status: "joined",
        userId: "mia",
      },
      {
        id: "call-participant-ana-ringing",
        initials: "NC",
        isCameraOn: false,
        isMuted: false,
        label: "Nivea Careli",
        presenceStatus: "online",
        role: "Operacao",
        status: "invited",
        userId: "ana",
      },
    ],
    startedAt: "09:32",
    status: "ringing",
    title: "Retorno rapido da cobranca",
    type: "audio",
  },
] as const satisfies readonly PulseXCallSession[];
